import React, { Fragment } from 'react';
import Head from 'next/head';
import { Box, Container, CssBaseline } from '@mui/material';
import AppHeader from '../../src/components/Items/AppHeader';
import { useRouter } from 'next/router';
import { useInit } from '../../src/components/constants';
import NearestMarket from '../../src/components/Home/NearestMarket';

const CategorizedProducts = () => {
  useInit();
  const router = useRouter();
  const { categoryCode } = router.query;

  return (
    <Fragment>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <title>KerPas</title>
      </Head>
      <CssBaseline />
      <AppHeader />
      <Container maxWidth={'lg'} sx={{ px: '0!important', overflow: 'hidden' }}>
        <Box py={1} mt={10} mb={8}>
          <NearestMarket />
        </Box>
      </Container>
    </Fragment>
  );
};

export default CategorizedProducts;
