import React, { Fragment, useEffect } from 'react';
import Head from 'next/head';
import { Box, Container, CssBaseline } from '@mui/material';
import AppHeader from '../../src/components/Items/AppHeader';
import { useRouter } from 'next/router';
import { checkUserData } from '../../src/components/constants';
import { setAuthUserDataR } from '../../src/redux/actions/authRActions';
import { useDispatch, useSelector } from 'react-redux';
import { rootReducerI } from '../../src/redux/reducers';

const CategorizedProducts = () => {
  const router = useRouter();
  const selector = useSelector((state: rootReducerI) => state);
  const dispatch = useDispatch();
  const { categoryCode } = router.query;

  useEffect(() => {
    checkUserData()
      .then(userData => {
        if (userData) {
          dispatch(setAuthUserDataR(userData));
        }
      })
      .catch(() => {});
  }, []);
  return (
    <Fragment>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <title>KerPas</title>
      </Head>
      <CssBaseline />
      <Container maxWidth={'lg'} sx={{ px: '0!important', overflow: 'hidden' }}>
        <Box py={1} mt={10} mb={8}>
          {categoryCode}
        </Box>
      </Container>
      <AppHeader />
    </Fragment>
  );
};

export default CategorizedProducts;
