import Head from 'next/head';
import AppHeader from '../src/components/Home/AppHeader';
import { Box, Container, CssBaseline, ThemeProvider } from '@mui/material';
import theme from '../src/config/theme';
import Campaign from '../src/components/Home/Campaign';
import axios from '../src/config/axios';
import { Fragment } from 'react';
import FeaturedServices from '../src/components/Home/FeaturedServices';
import { AutoFixHigh, Category } from '@mui/icons-material';
import Categories from '../src/components/Home/Categories';
import Stores from '../src/components/Home/Stores';

type HomeProps = {
  campaigns: {
    error: boolean;
    result: any[];
  };
};

export default function Home({ campaigns }: HomeProps) {
  const featuredServiceData = [
    {
      icon: function Icon() {
        return <AutoFixHigh />;
      },
      title: 'Segar & Higenis',
      subtitle: 'Produk pilihan',
      iconBgColor:
        'linear-gradient(47deg, rgba(255,164,26,1) 0%, rgba(255,203,107,1) 100%)',
    },
    {
      icon: function Icon() {
        return <AutoFixHigh />;
      },
      title: 'Timbangan Pasti Pas',
      subtitle: 'Sesuai ukuran / berat',
      iconBgColor:
        'linear-gradient(47deg, rgba(255,26,26,1) 0%, rgba(255,99,99,1) 100%)',
    },
    {
      icon: function Icon() {
        return <AutoFixHigh />;
      },
      title: 'Diantar 2 Kali Sehari',
      subtitle: 'Jam 9 pagi dan jam 3 sore',
      iconBgColor:
        'linear-gradient(47deg, rgba(26,42,255,1) 0%, rgba(89,101,255,1) 100%)',
    },
    {
      icon: function Icon() {
        return <AutoFixHigh />;
      },
      title: 'Lengkap & Murah',
      subtitle: 'Paling Lengkap dan harga pasar tradisional',
      iconBgColor:
        'linear-gradient(47deg, rgba(49,184,51,1) 0%, rgba(126,244,129,1) 100%)',
    },
  ];

  const fakeCats = [
    {
      imageUri:
        'https://demos.creative-tim.com/material-dashboard-pro-react/static/media/card-2.3159a3bb.jpeg',
      url: '',
      name: 'Beras',
    },
    {
      imageUri:
        'https://demos.creative-tim.com/material-dashboard-pro-react/static/media/card-3.ba9e3c5e.jpeg',
      url: '',
      name: 'Daging Sapi',
    },
    {
      imageUri:
        'https://demos.creative-tim.com/material-dashboard-pro-react/static/media/card-2.3159a3bb.jpeg',
      url: '',
      name: 'Ikan & Hasil Laut',
    },
    {
      imageUri:
        'https://demos.creative-tim.com/material-dashboard-pro-react/static/media/card-3.ba9e3c5e.jpeg',
      url: '',
      name: 'Bumbu Dapur',
    },
  ];

  const fakeStores = [
    {
      imageUri:
        'https://demos.creative-tim.com/material-dashboard-pro-react/static/media/card-2.3159a3bb.jpeg',
      url: '',
      name: 'Daeng Jony',
    },
    {
      imageUri:
        'https://demos.creative-tim.com/material-dashboard-pro-react/static/media/card-3.ba9e3c5e.jpeg',
      url: '',
      name: 'Daeng Lontong',
    },
    {
      imageUri:
        'https://demos.creative-tim.com/material-dashboard-pro-react/static/media/card-2.3159a3bb.jpeg',
      url: '',
      name: 'Pa\' Balue',
    },
    {
      imageUri:
        'https://demos.creative-tim.com/material-dashboard-pro-react/static/media/card-3.ba9e3c5e.jpeg',
      url: '',
      name: 'Toko Siska',
    },
    {
      imageUri:
        'https://demos.creative-tim.com/material-dashboard-pro-react/static/media/card-3.ba9e3c5e.jpeg',
      url: '',
      name: 'Daeng Sopa',
    },
    {
      imageUri:
        'https://demos.creative-tim.com/material-dashboard-pro-react/static/media/card-3.ba9e3c5e.jpeg',
      url: '',
      name: 'Manessa Laris',
    },
  ];

  return (
    <Fragment>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <title>KerPas</title>
      </Head>
      <CssBaseline />
      <AppHeader />
      <Container maxWidth={'lg'} sx={{ px: '0!important', overflow: 'hidden' }}>
        <Box my={8} py={1}>
          <Campaign data={campaigns.result} />
          <FeaturedServices data={featuredServiceData} />
          <Categories data={fakeCats} />
          <Stores data={fakeStores} />
        </Box>
      </Container>
    </Fragment>
  );
}

export const getStaticProps = async () => {
  // Call an external API endpoint to get posts.
  // You can use any data fetching library
  const { data: campaigns } = await axios.post('/ads/campaign', {
    category: '0',
  });

  // By returning { props: { posts } }, the Blog component
  // will receive `posts` as a prop at build time
  return {
    props: { campaigns },
  };
};
